### ISSUE TITLE
Error class org.apache.ignite.IgniteException: Default grid instance has already been started.

### ISSUE THREAD

**Issue by faithword** [ptupitsyn/ignite-net-examples#1]
I am trying to use this in an ASP.Net application but I keep getting this error - **Error class org.apache.ignite.IgniteException: Default grid instance has already been started.**

found this http://stackoverflow.com/questions/39162641/apache-ignite-gives-error-when-you-refresh-webpage but the solution Ignition.getOrStart() does not exist in Ignite.Net!

Please help!!! How do I configure this for a web app? (works fine in a console app.)

**Comment by ptupitsyn** [comment]
Closing the issue. This is a personal repository, and it does not represent Apache Ignite project. I'm glad to help with any Ignite questions when I can, but it would be better to ask them in official Ignite support channels, so that all community members can participate: https://ignite.apache.org/community/resources.html

Thanks!
